### ISSUE TITLE
Add DNS server option 

### ISSUE THREAD

**Issue by CleanMachine1** [Itai-Nelken/system-tools#23]
Hi, I have made a small bash script to set the DNS of a system, this is useful for someone who wants to use their pi-hole or just wants to use Google DNS (8.8.8.8) for example, heres a link to the repo https://github.com/CleanMachine1/Linux-DNS-Set

I will add it in a pull request if required!

**Comment by Itai-Nelken** [comment]
I'm not sure I know what a DNS server is lol. time to research.
is your script tested?

**Comment by CleanMachine1** [comment]
I done some testing earlier, I need to test whether it works on RPi-OS though, but it definitely works on Linux Mint :rofl:

**Comment by CleanMachine1** [comment]
DNS - In simple terms - 

Requested Website
DNS
Gives IP 


Computers don't read URLS they read IPs

**Comment by CleanMachine1** [comment]
OK, just grabbed my Portable Pi :) and run the script (found a bug with \n and fixed) and it definitely works!

I have a Pi-hole which blocks ads and heres the output from a ping to a well known ad website 
>$ ping doubleclick.net
PING doubleclick.net (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.078 ms

If it wasn't enabled it would be pinging an actual server rather than 127.0.0.1

**Comment by Itai-Nelken** [comment]
so I'll add it in 1.5.0!
see https://github.com/Itai-Nelken/Pi-Assistant/projects/2

**Comment by CleanMachine1** [comment]
Could you put
echo "Made By CleanMachine1"

at the top of the script? ;)

**Comment by Itai-Nelken** [comment]
> Could you put
> echo "Made By CleanMachine1"
> 
> at the top of the script? ;)

I'll credit you somehow, probably like that just in bold/different color:)

**Comment by CleanMachine1** [comment]
I have put a echo command at the top of the script followed by 3 seconds to read it

That does but you want to do all the colors and things I wont complain 👀

**Comment by Itai-Nelken** [comment]
I prefer to make the credit to not wait, but instead appear in a way that catches the eye.
here are some ideas:
- figlet: (install with apt) `figlet "This script was made by CleanMachine1"`
- figlet + lolcat (rainbow colors): (install with apt) `figlet "This script was made by CleanMachine1" | lolcat` the `-a` option can be added to lolcat so it prints the figlet from figlet (This script was made by CleanMachine1) line by line as well as in rainbow colors.
- simple colored + bold text
- simple colored + bold text + ascii graphic, for example:
```bash
echo '
        ___________________________________
______/This script was made by CleanMachine1\______
'
```
(I suck at ascii graphics as you see).
- cowsay with the tux character: (install with apt) `cowsay -f tux "This script was made by CleanMachine1"`(looks really cool in my opinion, can be piped to lolcat for it to be colorful).
output from cowsay with tux character (not actually colored):
```bash
< This script was made by CleanMachine1 >
----------
   \
    \
        .--.
       |o_o |
       |:_/ |
      //   \ \
     (|     | )
    /'\_   _/`\
    \___)=(___/
```
after that a 0.3 second sleep should be enough for it to be eye catching in my opinion.

***

also I'm probably going to add a 'Community script' category including your script and the one from #21.

**Comment by CleanMachine1** [comment]
Wow, I was very aware of the cowsay, lolcat and figlet but that cowsay tux is very cool!

I'll add another commit to my repo moving the change, and although you may have done it, I want that tux!

**Comment by CleanMachine1** [comment]
I'd say ignore lolcat as its bloated as it needs to install ruby
ignore cowsay as well and just copy the output of cowsay and put it in echo commands

**Comment by Itai-Nelken** [comment]
sounds good, but why ignore cowsay? because its a extra dependency?

**Comment by CleanMachine1** [comment]
Yes, why install more when it can be achieved easier

**Comment by CleanMachine1** [comment]
Hmm, actually I can't figure out a way to get the lines into a echo command as it takes all the backticks and other bash peices and takes them as commands 

+ Cowsay is a <100Kb install

**Comment by CleanMachine1** [comment]
Add This into the install script 

sudo apt install cowsay -y


Edit: I will add it into the script my self in my repo

**Comment by CleanMachine1** [comment]
I need some help..
as the script needs to be run as root, cowsay isn't under root due to it being a "game"

How can I set it to the main user for just that command, I also need it to be not just "pi" as not everyone has a default username

**Comment by CleanMachine1** [comment]
I am fully done 
Done a few commits 
You may want to remove the script if you have it installed as it has a lot of small bugs
I have added everything needed 

I fixed the cowsay by just directing it to run the binary straight from /usr/bin/games

**Comment by Itai-Nelken** [comment]
> Hmm, actually I can't figure out a way to get the lines into a echo command as it takes all the backticks and other bash peices and takes them as commands 

Use ' instead of "

**Comment by CleanMachine1** [comment]
Its fixed now, considering how light cowsay is, and how fun it is, I am sure the user can spare 100kb of data for a friendly tux, or block of cheese 
```
 _________________________
< I am a block of cheese! >
 -------------------------
   \
    \
      _____   _________
     /     \_/         |
    |                 ||
    |                 ||
   |    ###\  /###   | |
   |     0  \/  0    | |
  /|                 | |
 / |        <        |\ \
| /|                 | | |
| |     \_______/   |  | |
| |                 | / /
/||                 /|||
   ----------------|
        | |    | |
        ***    ***
       /___\  /___\

```

**Comment by Itai-Nelken** [comment]
Only complaint I have is that 3 seconds is to long for credits in my opinion, I would use 0.3 seconds because the big cowsay tux catches the eye, so no need to let it stay there for so long.
An alternative would be to find a way to keep the credits always at the top while the script runs.

Once that is done it will be added once I come round to implement all the stuff I want and release v1.5.0.

**Comment by CleanMachine1** [comment]
1 second and it will be 1 second!

**Comment by CleanMachine1** [comment]
Done and done!

The raw github link might take up to 5 mins to refresh

**Comment by CleanMachine1** [comment]
Ok, this will probably be my last commit for Linux-DNS-Set
I am going to change the scripts name from main.sh to DNSSet.sh otherwise it may conflict with other files

**Comment by CleanMachine1** [comment]
Not last commit but this might be

I took your idea of keeping the tu git commit -m "Added Clears and cowsays to keep the tux at the top
Sorry if you need to copy the script again :(

**Comment by Itai-Nelken** [comment]
I didn't start to add it yet , v1.5.0 will come in another 5 venus days (~4 earth years)...

**Comment by CleanMachine1** [comment]
Been a quarter of an earth year, ever plan to add this, if anyone is still using this

**Comment by Itai-Nelken** [comment]
TBH I abandoned this project. I think I might archive this repo.

**Comment by CleanMachine1** [comment]
:(

**Comment by Itai-Nelken** [comment]
I'm closing this issue as I have moved on to other things and don't have the time or interest to keep working on Pi-Assistant.
