### ISSUE TITLE
Github Backup Tool

### ISSUE THREAD

**Issue by slashtechno** [Itai-Nelken/system-tools#24]
Hello,

I made a script that backs up Github repositories and I was wondering if it could be added. 
The repo is [here](https://github.com/slashtechno/github-backup)

Thanks,
slashtechno

**Comment by Itai-Nelken** [comment]
Nice! I'll probably add it in the next release.
I'll start working on it soon™...

**Comment by slashtechno** [comment]
@Itai-Nelken  Thanks, also this will be put in the community scripts correct?

**Comment by Itai-Nelken** [comment]
Yes, or apps.

**Comment by Itai-Nelken** [comment]
I'm closing this issue as I have moved on to other things and don't have the time or interest to keep working on Pi-Assistant.
