### ISSUE TITLE
Make GUI dialog?

### ISSUE THREAD

**Issue by NoozAbooz** [Itai-Nelken/system-tools#3]
Have you thought about making a GUI dialog for this? You can use something like 
```sh
#!/bin/bash

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="Backtitle here"
TITLE="Title here"
MENU="Choose one of the following options:"

OPTIONS=(1 "Option 1"
         2 "Option 2"
         3 "Option 3")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "You chose Option 1"
            ;;
        2)
            echo "You chose Option 2"
            ;;
        3)
            echo "You chose Option 3"
            ;;
esac
```
To make a GUI that looks like 
![image](https://user-images.githubusercontent.com/44128563/97944713-9df41c00-1d42-11eb-9702-b5a48587fa45.png)

**Comment by Itai-Nelken** [comment]
yes, somtime in the future once I feel it has enough features and apps and is stable enough then I'll add a GUI.
anyway thanks for the suggestion and example, it will help me create it.

**Comment by Itai-Nelken** [comment]
@mobilegmYT the script you wrote doesn't run (at least for me)

**Comment by NoozAbooz** [comment]
Hmm. I think you can probably still google it.

**Comment by Itai-Nelken** [comment]
@mobilegmYT of course, thanks for suggesting anyway, but a gui is in 2nd place right now

**Comment by Itai-Nelken** [comment]
@mobilegmYT check the [new branch](https://github.com/Itai-Nelken/Pi-Assistant/tree/dialog-gui-testing), I added a dialog main menu!

**Comment by Itai-Nelken** [comment]
@mobilegmYT 
ok, I merged the branch! :partying_face:
now the main menu and app installer menu have a dialog GUI, each option still uses the old style (if needed), and there are some YAD pop-up windows in some of the scripts!

can you test it to see if everything works as it should?

**Comment by Itai-Nelken** [comment]
I'll close this issue in a days once I'm sure the new dialog GUI isn't causing any errors.

**Comment by Itai-Nelken** [comment]
the dialog gui is working great so far, thanks for suggesting it @mobilegmYT!
