### ISSUE TITLE
Adding More Scripts

### ISSUE THREAD

**Issue by slashtechno** [Itai-Nelken/system-tools#7]
Just a suggestion, you should add this to [Pi-Apps](https://github.com/botspot/pi-apps)

**Comment by Itai-Nelken** [comment]
I already tried [here](https://github.com/Botspot/pi-apps/issues/30) and Botspot declined.
I asked him again later and he said he doesn't wan't to add it.
I'm completly ok with it though, maybe one day Pi-Assistant will be useful enough for it to be added to pi-apps.

**Comment by slashtechno** [comment]
Oh okay. I think Pi-Assistant is **AMAZING!**

**Comment by Itai-Nelken** [comment]
> Oh okay. I think Pi-Assistant is **AMAZING!**

**Thanks a lot! I really appreciate it!**
really thanks so much for saying that, it means a lot for me!

what do you use it for? I mainly use it for the `system-info` feature.

**Comment by slashtechno** [comment]
I like that it can do some things like Raspi-Config and it can install apps like Pi-Apps. 
Also because [Pi-Apps](https://github.com/botspot/pi-apps) is open source is it possible to add some of the install and uninstall scripts?

**Comment by Itai-Nelken** [comment]
> I like that it can do some things like Raspi-Config and it can install apps like Pi-Apps.
> Also because [Pi-Apps](https://github.com/botspot/pi-apps) is open source is it possible to add some of the install and uninstall scripts?

you mean add some pi-apps scripts to Pi-Assistant?
if yes, then I don't want to do that.
Pi-Assistant is supposed to be something different then pi-apps or pikiss, and adding scripts from them won't help with that.

**Comment by slashtechno** [comment]
> you mean add some pi-apps scripts to Pi-Assistant?

I mean expanding Pi-Assistant's application install scripts.



> if yes, then I don't want to do that.
> Pi-Assistant is supposed to be something different then pi-apps or pikiss, and adding scripts from them won't help with that.

Oh okay.

**Comment by Itai-Nelken** [comment]
>I mean expanding Pi-Assistant's application install scripts.

I'll add scripts when I have a idea for one/one gets requested and I can add it.
while coding Pi-Assistant I learnt its a mistake to add to many scripts to fast.
also I learnt a lot since last time I re-wrote Pi-Assistant, so I'm currently in the proccess of bringing all scripts up to my newer standard.

if you have any specific request, feel free to ask for it and I'll add it if I can.

**Comment by slashtechno** [comment]
Thank you.

**Comment by Itai-Nelken** [comment]
@slashtechno I added a option to fix duplicates in the `/etc/apt/sources.list` file to the beta version of Pi-Assistant!
you can test it if you want, instructions are in the readme.

**Comment by slashtechno** [comment]
@Itai-Nelken  I really like the **idea** of Pi-Assistant but I feel that Pi-Assistant should focus on one click to execute a ton of commands. For example, downloading Kodi and setting up Netflix on it or setting up Pi-Hole.  I really do think Pi-Assistant is a very amazing idea

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken I really like the **idea** of Pi-Assistant but I feel that Pi-Assistant should focus on one click to execute a ton of commands. For example, downloading Kodi and setting up Netflix on it or setting up Pi-Hole. I really do think Pi-Assistant is a very amazing idea

I'll see what I can find to add to Pi-Assistant as long as its not on pi-apps or pikiss.

I am working on a box86 install script for 64bit OS's, and I'll see if I can find anything else that isn't done yet/isn't done in a good enough way in my opinion.

**Comment by slashtechno** [comment]
@Itai-Nelken What about Pi-Hole?

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken What about Pi-Hole?

I'll try :)

**Comment by Itai-Nelken** [comment]
I'm closing this issue as I have moved on to other things and don't have the time or interest to keep working on Pi-Assistant.
